version: '3.1'
services:
  expenses:
    build: '.'
    restart: always
    container_name: 'homebudget_dashboard'
    ports:
      - 8501:8501
    volumes:
      - homebudget_data:/app/data

volumes:
    homebudget_data:
        name: homebudget_data
